"""
Autogenerated module
"""

from datetime import datetime
from typing import List, Optional

from sqlmodel import Field, SQLModel

from aind_slims_api.tables.core import Quantity


class Content(SQLModel):
    """
    Autogenerated class for SLIMS table Content
    """

    __tablename__ = "Content"

    attachmentCount: Optional[int] = Field(default=None, title="attachmentCount")
    cntn_barCode: Optional[str] = Field(default=None, title="Barcode")
    cntn_cf_baselineWeight: Optional[Quantity] = Field(
        default=None, title="Baseline Weight"
    )
    cntn_cf_contactPerson: Optional[str] = Field(default=None, title="Contact Person")
    cntn_cf_dateOfBirth: Optional[datetime] = Field(default=None, title="Date of birth")
    cntn_cf_ehsBarcode: Optional[str] = Field(default=None, title="EHS Barcode")
    cntn_cf_expiryDate: Optional[datetime] = Field(default=None, title="Expiry date")
    cntn_cf_externalId: Optional[str] = Field(default=None, title="External ID")
    cntn_cf_fk_fundingCode: Optional[int] = Field(
        default=None, title="Project ID", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    cntn_cf_fk_labTeam: Optional[int] = Field(
        default=None, title="lab team", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    cntn_cf_fk_labTeamAcronym: Optional[int] = Field(
        default=None,
        title="lab team acronym",
        foreign_key="ReferenceDataRecord.rdrc_cf_abbreviation",
    )
    cntn_cf_fk_purityStandards: Optional[List[int]] = Field(
        default=None,
        title="Purity standards",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    cntn_cf_fk_reagentCatalogNumber: Optional[int] = Field(
        default=None,
        title="reagent REF number",
        foreign_key="ReferenceDataRecord.rdrc_cf_catalogNumber",
    )
    cntn_cf_fk_specialHandlingGuidelines: Optional[List[int]] = Field(
        default=None,
        title="Special handling guidelines",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    cntn_cf_fk_specialStorageGuidelines: Optional[List[int]] = Field(
        default=None,
        title="Special storage guidelines",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    cntn_cf_fk_storageTemp_dynChoice: Optional[int] = Field(
        default=None, title="Storage temp", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    cntn_cf_fluorescentProtein: Optional[List[str]] = Field(
        default=None, title="Fluorescent protein"
    )
    cntn_cf_genotype: Optional[str] = Field(default=None, title="Full Genotype")
    cntn_cf_iacucProtocol: Optional[str] = Field(default=None, title="IACUC Protocol")
    cntn_cf_intakeDate: Optional[datetime] = Field(default=None, title="intake date")
    cntn_cf_labtracksGroup: Optional[str] = Field(default=None, title="Breeding Group")
    cntn_cf_lightcycle: Optional[str] = Field(default=None, title="LightCycle")
    cntn_cf_lotNumber: Optional[str] = Field(default=None, title="Lot number")
    cntn_cf_mass: Optional[Quantity] = Field(default=None, title="Mass")
    cntn_cf_massRequired: Optional[Quantity] = Field(default=None, title="Mass (req.)")
    cntn_cf_mouseAge: Optional[int] = Field(default=None, title="Mouse age (mo)")
    cntn_cf_mouseXOffset: Optional[float] = Field(default=None, title="Mouse X offset")
    cntn_cf_mouseYOffset: Optional[float] = Field(default=None, title="Mouse Y offset")
    cntn_cf_mouseZOffset: Optional[float] = Field(default=None, title="Mouse Z offset")
    cntn_cf_openDate: Optional[datetime] = Field(default=None, title="Open Date")
    cntn_cf_parentBarcode: Optional[str] = Field(default=None, title="Parent barcode")
    cntn_cf_parentName: Optional[str] = Field(default=None, title="Parent Name")
    cntn_cf_ph_shortText: Optional[str] = Field(default=None, title="pH")
    cntn_cf_scientificPointOfContact: Optional[str] = Field(
        default=None, title="Scientific Point of Contact"
    )
    cntn_cf_sectionThickness: Optional[Quantity] = Field(
        default=None, title="Section thickness"
    )
    cntn_cf_sex: Optional[str] = Field(default=None, title="Sex")
    cntn_cf_slice: Optional[int] = Field(default=None, title="Slice #")
    cntn_cf_sliceSequence: Optional[int] = Field(
        default=None, title="Brain Slice sequence"
    )
    cntn_cf_solutionConcentration: Optional[str] = Field(
        default=None, title="concentration"
    )
    cntn_cf_tangentialPlaneSectioningReference: Optional[str] = Field(
        default=None, title="tangential plane sectioning reference"
    )
    cntn_cf_tissueOrientation: Optional[str] = Field(
        default=None, title="tissue orientation"
    )
    cntn_cf_volumeRequired: Optional[Quantity] = Field(
        default=None, title="Volume (req.)"
    )
    cntn_cf_waterRestricted: Optional[bool] = Field(
        default=None, title="Water Restricted"
    )
    cntn_collectionDate: Optional[datetime] = Field(
        default=None, title="Collection date"
    )
    cntn_createdBy: Optional[str] = Field(default=None, title="Created by")
    cntn_createdOn: Optional[datetime] = Field(default=None, title="Created on")
    cntn_dilutionFactor: Optional[float] = Field(default=None, title="Dilution Factor")
    cntn_externalId: Optional[str] = Field(default=None, title="External Id")
    cntn_fk_category: Optional[int] = Field(
        default=None, title="Category", foreign_key="ContentType.cntp_name"
    )
    cntn_fk_containerContentType: Optional[int] = Field(
        default=None, title="Container type", foreign_key="ContentType.cntp_name"
    )
    cntn_fk_contentType: Optional[int] = Field(
        default=None, title="Type", foreign_key="ContentType.cntp_name"
    )
    cntn_fk_disease: Optional[int] = Field(
        default=None, title="Disease", foreign_key="Disease.diss_name"
    )
    cntn_fk_group: Optional[int] = Field(
        default=None, title="Group", foreign_key="Groups.grps_groupName"
    )
    cntn_fk_location: Optional[int] = Field(
        default=None, title="Location", foreign_key="Location.lctn_name"
    )
    cntn_fk_location_recursive: Optional[int] = Field(
        default=None,
        title="Location (including sublocations)",
        foreign_key="Location.lctn_name",
    )
    cntn_fk_originalContent: Optional[int] = Field(
        default=None, title="Original Content", foreign_key="Content.cntn_id"
    )
    cntn_fk_product: Optional[int] = Field(
        default=None, title="Product", foreign_key="Product.prdc_name"
    )
    cntn_fk_product_strain: Optional[int] = Field(
        default=None,
        title="Product (filtering without version)",
        foreign_key="Product.prdc_name",
    )
    cntn_fk_provider: Optional[int] = Field(
        default=None, title="Provider", foreign_key="Provider.prvd_name"
    )
    cntn_fk_source: Optional[int] = Field(
        default=None, title="manufacturer", foreign_key="Source.sorc_name"
    )
    cntn_fk_status: Optional[int] = Field(
        default=None, title="Status", foreign_key="Status.stts_name"
    )
    cntn_fk_user: Optional[int] = Field(
        default=None, title="User", foreign_key="User.user_userName"
    )
    cntn_id: Optional[str] = Field(default=None, title="Name")
    cntn_modifiedBy: Optional[str] = Field(default=None, title="Modified by")
    cntn_modifiedOn: Optional[datetime] = Field(default=None, title="Modified on")
    cntn_originalContentBarCode: Optional[str] = Field(
        default=None, title="Original content barcode"
    )
    cntn_pk: int = Field(..., title="cntn_pk", primary_key=True)
    cntn_position_column: Optional[str] = Field(default=None, title="Located at column")
    cntn_position_row: Optional[str] = Field(default=None, title="Located at row")
    cntn_quantity: Optional[float] = Field(default=None, title="Quantity")
    cntn_status: Optional[str] = Field(default=None, title="Status")
    cntn_unit: Optional[str] = Field(default=None, title="Unit")
    cntp_canEnrollInStudy: Optional[bool] = Field(
        default=None, title="Can enroll in a study"
    )
    cntp_containerType: Optional[bool] = Field(
        default=None, title="Is a container type"
    )
    cntp_name: Optional[str] = Field(default=None, title="Name")
    cntp_slimsGeneratesBarcode: Optional[bool] = Field(
        default=None, title="SLIMS generates a barcode for content of this type"
    )
    cntp_useBarcodeAsId: Optional[bool] = Field(default=None, title="Use barcode as id")
    containerIcon: Optional[str] = Field(default=None, title="Container icon")
    derivedCount: Optional[int] = Field(default=None, title="Derivation count")
    diss_name: Optional[str] = Field(default=None, title="Name")
    father: Optional[int] = Field(
        default=None, title="Father", foreign_key="Content.cntn_id"
    )
    father_display: Optional[str] = Field(default=None, title="father_display")
    flags: Optional[int] = Field(
        default=None, title="Flags", foreign_key="ContentEventType.cnvt_name"
    )
    grps_groupName: Optional[str] = Field(default=None, title="Name")
    icon: Optional[str] = Field(default=None, title="Icon")
    ingredientCount: Optional[int] = Field(default=None, title="Ingredient count")
    isNaFilter: Optional[str] = Field(default=None, title="Field is N/A")
    isNotNaFilter: Optional[str] = Field(default=None, title="Field is not N/A")
    lctn_barCode: Optional[str] = Field(default=None, title="Barcode")
    lctn_columns: Optional[str] = Field(default=None, title="Columns")
    lctn_name: Optional[str] = Field(default=None, title="Name")
    lctn_rows: Optional[str] = Field(default=None, title="Rows")
    lctp_positionLess: Optional[bool] = Field(
        default=None, title="Don't require positions"
    )
    locationPath: Optional[str] = Field(default=None, title="Location path")
    mixCount: Optional[int] = Field(default=None, title="Mix count")
    mother: Optional[int] = Field(
        default=None, title="Mother", foreign_key="Content.cntn_id"
    )
    mother_display: Optional[str] = Field(default=None, title="mother_display")
    previousFlags: Optional[int] = Field(
        default=None, title="Previous flags", foreign_key="ContentEventType.cnvt_name"
    )
    prvd_name: Optional[str] = Field(default=None, title="Name")
    relationToProband: Optional[str] = Field(default=None, title="Relation to proband")
    sorc_name: Optional[str] = Field(default=None, title="Name")
    stts_name: Optional[str] = Field(default=None, title="Name")
    user_userName: Optional[str] = Field(default=None, title="User name")
    xprs_input: Optional[int] = Field(default=None, title="xprs_input")
    xprs_output: Optional[int] = Field(default=None, title="xprs_output")
