"""
Autogenerated module
"""

from datetime import datetime
from typing import List, Optional

from sqlmodel import Field, SQLModel

from aind_slims_api.tables.core import Quantity


class Order(SQLModel):
    """
    Autogenerated class for SLIMS table Order
    """

    __tablename__ = "Order"

    attachmentCount: Optional[int] = Field(default=None, title="attachmentCount")
    grps_groupName: Optional[str] = Field(default=None, title="Name")
    linkedContentCount: Optional[int] = Field(default=None, title="# content")
    ordr_barCode: Optional[str] = Field(default=None, title="Barcode")
    ordr_cf_aPInjectionCoordinate: Optional[float] = Field(
        default=None, title="A/P Injection Coordinate"
    )
    ordr_cf_aliquotBiosafetyLevel: Optional[str] = Field(
        default=None, title="Aliquot Biosafety Level"
    )
    ordr_cf_aliquotLabel1: Optional[str] = Field(default=None, title="Aliquot Label")
    ordr_cf_aliquotStorageLocation1: Optional[str] = Field(
        default=None, title="Aliquot storage location"
    )
    ordr_cf_blockingSolution: Optional[str] = Field(
        default=None, title="Blocking solution"
    )
    ordr_cf_blockingSolutionResOps: Optional[str] = Field(
        default=None, title="Blocking solution"
    )
    ordr_cf_careModule: Optional[str] = Field(default=None, title="Care Module")
    ordr_cf_collectionFrequency: Optional[str] = Field(
        default=None, title="Collection Frequency"
    )
    ordr_cf_craniotomyType: Optional[str] = Field(default=None, title="Craniotomy Type")
    ordr_cf_dV1InjectionCoordinate: Optional[float] = Field(
        default=None, title="D/V1 Injection Coordinate"
    )
    ordr_cf_dV2InjectionCoordinate: Optional[float] = Field(
        default=None, title="D/V2 Injection Coordinate"
    )
    ordr_cf_dye: Optional[str] = Field(default=None, title="Dye")
    ordr_cf_expectedOrActualPerfusionDate: Optional[datetime] = Field(
        default=None, title="Expected or Actual Perfusion Date"
    )
    ordr_cf_fixedIn30Sucrose: Optional[bool] = Field(
        default=None, title="Has the brain been fixed in 30% sucrose?"
    )
    ordr_cf_fk_brainStructure: Optional[int] = Field(
        default=None,
        title="brain structure",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    ordr_cf_fk_depreciatedDummyField: Optional[int] = Field(
        default=None, title="DEPRECIATED dummy field", foreign_key="Order.ordr_barCode"
    )
    ordr_cf_fk_hcrPanel: Optional[int] = Field(
        default=None, title="HCR Panel", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    ordr_cf_fk_primaryAntibody1: Optional[int] = Field(
        default=None, title="Primary Antibody", foreign_key="Content.cntn_id"
    )
    ordr_cf_fk_primaryAntibody2: Optional[int] = Field(
        default=None, title="Primary Antibody #2", foreign_key="Content.cntn_id"
    )
    ordr_cf_fk_primaryAntibody3: Optional[int] = Field(
        default=None, title="Primary Antibody #3", foreign_key="Content.cntn_id"
    )
    ordr_cf_fk_requestedClearingMethod: Optional[int] = Field(
        default=None,
        title="Requested clearing method",
        foreign_key="ExperimentTemplate.xptm_name",
    )
    ordr_cf_fk_requestedReagent: Optional[int] = Field(
        default=None, title="Requested Reagent", foreign_key="ContentType.cntp_name"
    )
    ordr_cf_fk_rhTest: Optional[int] = Field(
        default=None, title="RH-Test", foreign_key="ExperimentTemplate.xptm_name"
    )
    ordr_cf_fk_secondaryAntibody1: Optional[int] = Field(
        default=None, title="Secondary Antibody", foreign_key="Content.cntn_id"
    )
    ordr_cf_fk_secondaryAntibody2: Optional[int] = Field(
        default=None, title="Secondary Antibody #2", foreign_key="Content.cntn_id"
    )
    ordr_cf_fk_secondaryAntibody3: Optional[int] = Field(
        default=None, title="Secondary Antibody #3", foreign_key="Content.cntn_id"
    )
    ordr_cf_fk_tangentialPlaneSectioningReference: Optional[int] = Field(
        default=None,
        title="Tangential plane sectioning reference",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    ordr_cf_fluorescenceChannelsCcfReg: Optional[str] = Field(
        default=None, title="Fluorescence Channels - CCF Registration"
    )
    ordr_cf_fluorescenceChannelsCellSegmentation: Optional[List[str]] = Field(
        default=None, title="Fluorescence Channels - Cell Segmentation"
    )
    ordr_cf_fluorescenceChannelsImaging: Optional[List[str]] = Field(
        default=None, title="Fluorescence Channels - Imaging"
    )
    ordr_cf_fluorescenceChannelsStitching: Optional[str] = Field(
        default=None, title="Fluorescence Channels - Stitching"
    )
    ordr_cf_headpost: Optional[str] = Field(default=None, title="Headpost")
    ordr_cf_hemisphere: Optional[str] = Field(default=None, title="Hemisphere")
    ordr_cf_histologyPurpose: Optional[str] = Field(
        default=None, title="Histology purpose"
    )
    ordr_cf_implantIdCoverslipType: Optional[str] = Field(
        default=None, title="Implant ID/Coverslip Type"
    )
    ordr_cf_injectionAngle: Optional[int] = Field(default=None, title="Injection Angle")
    ordr_cf_intendedCcfTarget: Optional[List[str]] = Field(
        default=None, title="Intended CCF Target"
    )
    ordr_cf_lightCycle: Optional[str] = Field(default=None, title="Light Cycle")
    ordr_cf_location1APInjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 1  A/P Injection Coordinate"
    )
    ordr_cf_location1AliquotBiosafetyLevel: Optional[str] = Field(
        default=None, title="Location 1 Aliquot Biosafety Level"
    )
    ordr_cf_location1AliquotLabel: Optional[str] = Field(
        default=None, title="Location 1 Aliquot Label"
    )
    ordr_cf_location1AliquotStorageLocation: Optional[str] = Field(
        default=None, title="Location 1 Aliquot Storage Location"
    )
    ordr_cf_location1DV1InjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 1 D/V1 Injection Coordinate"
    )
    ordr_cf_location1DV2InjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 1 D/V 2 Injection Coordinate"
    )
    ordr_cf_location1Hemisphere: Optional[str] = Field(
        default=None, title="Location 1 Hemisphere"
    )
    ordr_cf_location1InjectionAngle: Optional[int] = Field(
        default=None, title="Location 1 Injection Angle"
    )
    ordr_cf_location1InjectionVolumePerDepth: Optional[int] = Field(
        default=None, title="Location 1 Injection Volume Per Depth"
    )
    ordr_cf_location1MLInjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 1 M/L Injection Coordinate"
    )
    ordr_cf_location2: Optional[bool] = Field(default=None, title="Location 2")
    ordr_cf_location2APInjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 2 A/P Injection Coordinate"
    )
    ordr_cf_location2AliquotBiosafetyLevel: Optional[str] = Field(
        default=None, title="Location 2 Aliquot Biosafety Level"
    )
    ordr_cf_location2AliquotLabel: Optional[str] = Field(
        default=None, title="Location 2 Aliquot Label"
    )
    ordr_cf_location2AliquotStorageLocation: Optional[str] = Field(
        default=None, title="Location 2 Aliquot Storage Location"
    )
    ordr_cf_location2DV1InjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 2 D/V1 Injection Coordinate"
    )
    ordr_cf_location2DV2InjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 2 D/V 2 Injection Coordinate"
    )
    ordr_cf_location2Hemisphere: Optional[str] = Field(
        default=None, title="Location 2 Hemisphere"
    )
    ordr_cf_location2InjectionAngle: Optional[int] = Field(
        default=None, title="Location 2 Injection Angle"
    )
    ordr_cf_location2InjectionVolumePerDepth: Optional[int] = Field(
        default=None, title="Location 2 Injection Volume Per Depth"
    )
    ordr_cf_location2MLInjectionCoordinate: Optional[float] = Field(
        default=None, title="Location 2 M/L Injection Coordinate"
    )
    ordr_cf_mLInjectionCoordinate: Optional[float] = Field(
        default=None, title="M/L Injection Coordinate"
    )
    ordr_cf_mondayOfRequestedWeekOfSurgery: Optional[datetime] = Field(
        default=None, title="Monday of Requested Week of Surgery"
    )
    ordr_cf_mountingMedia: Optional[str] = Field(default=None, title="Mounting media")
    ordr_cf_orderName: Optional[str] = Field(default=None, title="Order name")
    ordr_cf_performImmunolabeling: Optional[bool] = Field(
        default=None, title="Perform Immunolabeling?"
    )
    ordr_cf_pointOfContact: Optional[List[str]] = Field(
        default=None, title="Point of Contact"
    )
    ordr_cf_postFixSolution: Optional[str] = Field(
        default=None, title="Post-fix solution"
    )
    ordr_cf_primaryAntibody: Optional[str] = Field(
        default=None, title="Primary Antibody"
    )
    ordr_cf_procedure: Optional[str] = Field(default=None, title="Surgical Procedure")
    ordr_cf_requestBrainEmbedded: Optional[bool] = Field(
        default=None, title="Request brain embedded?"
    )
    ordr_cf_requestReferenceImages: Optional[str] = Field(
        default=None, title="Request Reference Atlas Numbers"
    )
    # The name for this field in SLIMS contains a dash. The '-' might be a typo.
    ordr_cf_requestedHistologyWorkflow_multi: Optional[List[str]] = Field(
        default=None,
        title="Requested Histology Workflow",
        alias="ordr_cf_requestedHistologyWorkflow-multi",
    )
    ordr_cf_requestedOrientation: Optional[str] = Field(
        default=None, title="slice orientation"
    )
    ordr_cf_requestedSectionThicknessM: Optional[str] = Field(
        default=None, title="Requested Section Thickness (&micro;m)"
    )
    ordr_cf_requestorComments: Optional[str] = Field(
        default=None, title="Requestor Comments"
    )
    ordr_cf_retainBrain: Optional[bool] = Field(
        default=None,
        title=(
            "Retain brain? (Brains will be discarded based on Tissue Sample Guidelines)"
        ),
    )
    ordr_cf_rnaseFree: Optional[bool] = Field(default=None, title="RNase free?")
    ordr_cf_secondaryAntibody: Optional[str] = Field(
        default=None, title="Secondary Antibody"
    )
    ordr_cf_sliceThickness: Optional[Quantity] = Field(
        default=None, title="slice thickness "
    )
    ordr_cf_specialInstructions: Optional[str] = Field(
        default=None, title="Special instructions"
    )
    ordr_cf_well: Optional[str] = Field(default=None, title="Well")
    ordr_createdBy: Optional[str] = Field(default=None, title="Created by")
    ordr_createdOn: Optional[datetime] = Field(default=None, title="Created on")
    ordr_fk_batch: Optional[int] = Field(
        default=None, title="Batch", foreign_key="Content.cntn_id"
    )
    ordr_fk_group: Optional[int] = Field(
        default=None, title="Group", foreign_key="Groups.grps_groupName"
    )
    ordr_fk_orderGroup: Optional[int] = Field(default=None, title="Order group")
    ordr_fk_orderType: Optional[int] = Field(
        default=None, title="Order type", foreign_key="OrderType.rdtp_name"
    )
    ordr_fk_previousStatus: Optional[int] = Field(
        default=None, title="Previous status", foreign_key="Status.stts_name"
    )
    ordr_fk_project: Optional[int] = Field(
        default=None, title="Project", foreign_key="Project.prjc_name"
    )
    ordr_fk_stabilityStudy: Optional[int] = Field(
        default=None, title="Stability Study", foreign_key="StabilityStudy.stsd_name"
    )
    ordr_fk_stabilityStudyStorage: Optional[int] = Field(
        default=None,
        title="Storage condition",
        foreign_key="StabilityStudyStorage.sssr_uniqueIdentifier",
    )
    ordr_fk_stabilityStudyTimepoint: Optional[int] = Field(
        default=None,
        title="Timepoint",
        foreign_key="StabilityStudyTimepoint.sstp_uniqueIdentifier",
    )
    ordr_fk_status: Optional[int] = Field(
        default=None, title="Status", foreign_key="Status.stts_name"
    )
    ordr_fk_timepointEnrollment: Optional[int] = Field(
        default=None,
        title="Timepoint enrollment",
        foreign_key="TimepointEnrollment.tpnr_uniqueIdentifier",
    )
    ordr_fk_user: Optional[int] = Field(
        default=None, title="User", foreign_key="User.user_userName"
    )
    ordr_modifiedBy: Optional[str] = Field(default=None, title="Modified by")
    ordr_modifiedOn: Optional[datetime] = Field(default=None, title="Modified on")
    ordr_pk: int = Field(..., title="ordr_pk", primary_key=True)
    ordr_plannedOnDate: Optional[datetime] = Field(
        default=None, title="Planned on date"
    )
    ordr_plannedOnTime: Optional[datetime] = Field(
        default=None, title="Planned on time"
    )
    ordr_slimsGeneratesBarcode: Optional[bool] = Field(
        default=None, title="ordr_slimsGeneratesBarcode"
    )
    prjc_name: Optional[str] = Field(default=None, title="Name")
    rdtp_type: Optional[str] = Field(default=None, title="Type")
    stts_name: Optional[str] = Field(default=None, title="Name")
    stts_namePrevious: Optional[str] = Field(default=None, title="stts_namePrevious")
    user_userName: Optional[str] = Field(default=None, title="User name")
