"""
Autogenerated module
"""

from datetime import datetime
from typing import List, Optional

from sqlmodel import Field, SQLModel

from aind_slims_api.tables.core import Quantity


class ReferenceDataRecord(SQLModel):
    """
    Autogenerated class for SLIMS table ReferenceDataRecord
    """

    __tablename__ = "ReferenceDataRecord"

    attachmentCount: Optional[int] = Field(default=None, title="attachmentCount")
    rdrc_active: Optional[bool] = Field(default=None, title="Active")
    rdrc_cf_HCRRounds: Optional[int] = Field(default=None, title="number of rounds")
    rdrc_cf_abbreviation: Optional[str] = Field(default=None, title="Abbreviation")
    rdrc_cf_acronym: Optional[str] = Field(default=None, title="Acronym")
    rdrc_cf_addgeneId: Optional[str] = Field(default=None, title="Addgene ID")
    rdrc_cf_additinalInfo: Optional[bool] = Field(
        default=None, title="Did the insertion attempt succeed?"
    )
    rdrc_cf_additionalWashReagent: Optional[str] = Field(
        default=None, title="Y Direction"
    )
    rdrc_cf_annotation: Optional[str] = Field(default=None, title="Annotation")
    rdrc_cf_antibodyTarget: Optional[str] = Field(default=None, title="Target")
    rdrc_cf_arcAngle: Optional[Quantity] = Field(default=None, title="Arc Angle")
    rdrc_cf_assemblyName: Optional[str] = Field(default=None, title="Assembly Name")
    rdrc_cf_atlasId: Optional[str] = Field(default=None, title="Atlas ID")
    rdrc_cf_batchId: Optional[str] = Field(default=None, title="Batch ID")
    rdrc_cf_biosafetyLevel: Optional[str] = Field(default=None, title="biosafety level")
    rdrc_cf_bsl: Optional[int] = Field(default=None, title="Implant Hole")
    rdrc_cf_businessUnit: Optional[str] = Field(default=None, title="Business Unit")
    rdrc_cf_calibrationDate: Optional[datetime] = Field(
        default=None, title="Calibration date"
    )
    rdrc_cf_casNumber: Optional[str] = Field(default=None, title="CAS number")
    rdrc_cf_catalogNumber: Optional[str] = Field(default=None, title="Catalog Number")
    rdrc_cf_ccfVersion: Optional[str] = Field(default=None, title="CCF Version")
    rdrc_cf_color: Optional[str] = Field(default=None, title="color")
    rdrc_cf_concentration: Optional[str] = Field(default=None, title="Concentration")
    rdrc_cf_concentrationQuant: Optional[Quantity] = Field(
        default=None, title="Concentration_quant"
    )
    rdrc_cf_custom: Optional[str] = Field(default=None, title="Custom")
    rdrc_cf_description_shortText: Optional[str] = Field(
        default=None, title="description"
    )
    rdrc_cf_deviceNameFC: Optional[str] = Field(default=None, title="Device Name")
    rdrc_cf_emissionWavelength_quant: Optional[Quantity] = Field(
        default=None, title="Emission wavelength"
    )
    rdrc_cf_excitationWavelength_quant: Optional[Quantity] = Field(
        default=None, title="Excitation wavelength"
    )
    rdrc_cf_expirationDate: Optional[datetime] = Field(
        default=None, title="Expiration date"
    )
    rdrc_cf_fiberNames: Optional[str] = Field(default=None, title="Fiber names")
    rdrc_cf_firstName: Optional[str] = Field(default=None, title="first name")
    rdrc_cf_fk_allowedContentType: Optional[int] = Field(
        default=None, title="allowed content type", foreign_key="ContentType.cntp_name"
    )
    rdrc_cf_fk_antibodyCloneType: Optional[int] = Field(
        default=None, title="Clone type", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_antibodyConjugationState: Optional[int] = Field(
        default=None,
        title="Conjugation state",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_antibodyFluorophore: Optional[int] = Field(
        default=None, title="Fluorophore", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_antibodyHostSpecies: Optional[int] = Field(
        default=None, title="Host species", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_antibodyType: Optional[int] = Field(
        default=None, title="Antibody type", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_department: Optional[int] = Field(
        default=None, title="Department", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_dye: Optional[int] = Field(
        default=None, title="Dye", foreign_key="Content.cntn_id"
    )
    rdrc_cf_fk_dyeType: Optional[int] = Field(
        default=None, title="dye type", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_fiberConnections2: Optional[List[int]] = Field(
        default=None,
        title="Fiber Connections",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_hcrSeriesName: Optional[int] = Field(
        default=None,
        title="HCR Series Name",
        foreign_key="ReferenceDataRecord.rdrc_cf_seriesName",
    )
    rdrc_cf_fk_labTeam: Optional[int] = Field(
        default=None, title="lab team", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_manufacturer: Optional[int] = Field(
        default=None, title="Manufacturer", foreign_key="Source.sorc_name"
    )
    rdrc_cf_fk_organization: Optional[int] = Field(
        default=None, title="Organization", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_primaryTargetedStructure: Optional[int] = Field(
        default=None,
        title="Primary Targeted Structure",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_probesByRound: Optional[List[int]] = Field(
        default=None,
        title="Probes By Round",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_probesList: Optional[List[int]] = Field(
        default=None, title="Probes List", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_protocol: Optional[int] = Field(
        default=None, title="Protocol", foreign_key="Sop.stop_name"
    )
    rdrc_cf_fk_purityStandards: Optional[List[int]] = Field(
        default=None,
        title="Purity standards",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_reagents: Optional[int] = Field(
        default=None, title="Reagents", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_rewardSpouts: Optional[int] = Field(
        default=None, title="Reward Spouts", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_fk_rigInstrument: Optional[int] = Field(
        default=None, title="Instrument", foreign_key="Instrument.nstr_name"
    )
    rdrc_cf_fk_secondaryTargetedStructures2: Optional[List[int]] = Field(
        default=None,
        title="Secondary Targeted Structures",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_specialHandlingGuidelines: Optional[List[int]] = Field(
        default=None,
        title="Special handling guidelines",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_specialStorageGuidelines: Optional[List[int]] = Field(
        default=None,
        title="Special storage guidelines",
        foreign_key="ReferenceDataRecord.rdrc_name",
    )
    rdrc_cf_fk_storageTemp_dynChoice: Optional[int] = Field(
        default=None, title="Storage temp", foreign_key="ReferenceDataRecord.rdrc_name"
    )
    rdrc_cf_form: Optional[str] = Field(default=None, title="form")
    rdrc_cf_fundingSource: Optional[str] = Field(default=None, title="Funding Source")
    rdrc_cf_geneTarget: Optional[str] = Field(default=None, title="gene target")
    rdrc_cf_hostSpecies: Optional[str] = Field(default=None, title="X Direction")
    rdrc_cf_hyperlink: Optional[str] = Field(default=None, title="Hyperlink")
    rdrc_cf_ignoreFileRequirement: Optional[bool] = Field(
        default=None, title="Ignore file requirement"
    )
    rdrc_cf_implantTargetingGuide: Optional[int] = Field(
        default=None,
        title="Implant Targeting Guide",
        foreign_key="Attachment.attm_name",
    )
    rdrc_cf_initiator: Optional[str] = Field(default=None, title="Amplifier")
    rdrc_cf_inputCalibrations: Optional[str] = Field(default=None, title="Input Key")
    rdrc_cf_inputValues: Optional[str] = Field(default=None, title="Input Values")
    rdrc_cf_jsonAttachment: Optional[int] = Field(
        default=None, title="JSON Attachment", foreign_key="Attachment.attm_name"
    )
    rdrc_cf_laserExcitationPower: Optional[Quantity] = Field(
        default=None, title="Laser Excitation Power"
    )
    rdrc_cf_laserName: Optional[str] = Field(default=None, title="Laser name")
    rdrc_cf_laserWavelength: Optional[Quantity] = Field(
        default=None, title="Laser Wavelength"
    )
    rdrc_cf_lastName: Optional[str] = Field(default=None, title="last name")
    rdrc_cf_lightEmittingDiodeExcitationPower: Optional[Quantity] = Field(
        default=None, title="Light emitting diode excitation power"
    )
    rdrc_cf_lightEmittingDiodeN: Optional[str] = Field(
        default=None, title="Light emitting diode name"
    )
    rdrc_cf_limsId: Optional[int] = Field(default=None, title="LIMS ID")
    rdrc_cf_lotNumberReagent: Optional[str] = Field(default=None, title="Lot number")
    rdrc_cf_manipulatorCalibrations: Optional[int] = Field(
        default=None, title="Coordinate Transform", foreign_key="Attachment.attm_name"
    )
    rdrc_cf_manipulatorX: Optional[Quantity] = Field(
        default=None, title="Manipulator X"
    )
    rdrc_cf_manipulatorZ: Optional[Quantity] = Field(
        default=None, title="Manipulator Z"
    )
    rdrc_cf_manipulatory: Optional[Quantity] = Field(
        default=None, title="Manipulator Y"
    )
    rdrc_cf_manufacturerInfo: Optional[int] = Field(
        default=None, title="manufacturer info", foreign_key="Attachment.attm_name"
    )
    rdrc_cf_mass: Optional[Quantity] = Field(default=None, title="Mass")
    rdrc_cf_message: Optional[str] = Field(default=None, title="Message")
    rdrc_cf_moduleAngle: Optional[Quantity] = Field(default=None, title="Module Angle")
    rdrc_cf_notes: Optional[str] = Field(default=None, title="Notes")
    rdrc_cf_notesCalibrations: Optional[str] = Field(
        default=None, title="Specify Reward Solution"
    )
    rdrc_cf_notesSettings: Optional[str] = Field(default=None, title="Notes/settings")
    rdrc_cf_numberOfProbesPerRound: Optional[int] = Field(
        default=None, title="number of probes per round"
    )
    rdrc_cf_outputCalibrations: Optional[str] = Field(default=None, title="Output Key")
    rdrc_cf_outputValues: Optional[str] = Field(default=None, title="Output Values")
    rdrc_cf_patchCordName: Optional[str] = Field(default=None, title="Patch cord name")
    rdrc_cf_patchCordOutputPower: Optional[Quantity] = Field(
        default=None, title="Patch cord output power"
    )
    rdrc_cf_ph_shorttext: Optional[str] = Field(default=None, title="pH")
    rdrc_cf_plasmidMap: Optional[int] = Field(
        default=None,
        title="Brain Orientation Image",
        foreign_key="Attachment.attm_name",
    )
    rdrc_cf_probeName: Optional[str] = Field(default=None, title="Ephys Probe Name")
    rdrc_cf_projectCode: Optional[str] = Field(default=None, title="Project Code")
    rdrc_cf_protocolIdMaintenance: Optional[str] = Field(
        default=None, title="DEPRECATED Protocol ID"
    )
    rdrc_cf_rewardSolution: Optional[str] = Field(default=None, title="Reward Solution")
    rdrc_cf_rotationAngle: Optional[Quantity] = Field(
        default=None, title="Rotation Angle"
    )
    rdrc_cf_rounds: Optional[int] = Field(default=None, title="round number")
    rdrc_cf_rrid: Optional[str] = Field(default=None, title="RRID")
    rdrc_cf_safeName: Optional[str] = Field(default=None, title="Safe Name")
    rdrc_cf_seriesName: Optional[str] = Field(default=None, title="Series Name")
    rdrc_cf_shelfLifeOpened_quant: Optional[Quantity] = Field(
        default=None, title="Shelf life (opened)"
    )
    rdrc_cf_shelfLifeUnopened_quant: Optional[Quantity] = Field(
        default=None, title="Shelf life (unopened)"
    )
    rdrc_cf_sourceReagent: Optional[str] = Field(default=None, title="Source")
    rdrc_cf_speakerName: Optional[str] = Field(default=None, title="Speaker name")
    rdrc_cf_speakerVolume: Optional[Quantity] = Field(
        default=None, title="Speaker volume"
    )
    rdrc_cf_species: Optional[str] = Field(default=None, title="species")
    rdrc_cf_speciesName: Optional[str] = Field(default=None, title="common name")
    rdrc_cf_spoutSide: Optional[str] = Field(default=None, title="Spout Side")
    rdrc_cf_stainType: Optional[str] = Field(default=None, title="stain type")
    rdrc_cf_startingMass: Optional[Quantity] = Field(
        default=None, title="Starting mass"
    )
    rdrc_cf_startingPosition: Optional[str] = Field(
        default=None, title="Starting Position"
    )
    rdrc_cf_startingVolume: Optional[Quantity] = Field(
        default=None, title="Starting volume"
    )
    rdrc_cf_stimulusName: Optional[str] = Field(
        default=None, title="Stimulus device name"
    )
    rdrc_cf_subcellularLocalization_ST: Optional[str] = Field(
        default=None, title="SubCellular Localization"
    )
    # The name for this field in SLIMS contains a dash. The '-' might be a typo.
    rdrc_cf_surface_Z: Optional[Quantity] = Field(
        default=None, title="Surface Z", alias="rdrc_cf_surface-Z"
    )
    rdrc_cf_targetAp: Optional[Quantity] = Field(default=None, title="Bregma Target AP")
    rdrc_cf_targetDv: Optional[Quantity] = Field(default=None, title="Bregma Target DV")
    rdrc_cf_targetMl: Optional[Quantity] = Field(default=None, title="Bregma Target ML")
    rdrc_cf_targetedCcfCoordinatesAp: Optional[Quantity] = Field(
        default=None, title="CCF Coordinates (AP)"
    )
    rdrc_cf_targetedCcfCoordinatesDv: Optional[Quantity] = Field(
        default=None, title="CCF Coordinates (DV)"
    )
    rdrc_cf_targetedCcfCoordinatesMl: Optional[Quantity] = Field(
        default=None, title="CCF Coordinates (ML)"
    )
    rdrc_cf_targetedLayers: Optional[List[str]] = Field(
        default=None, title="targeted layers"
    )
    rdrc_cf_temperature: Optional[Quantity] = Field(default=None, title="temperature")
    rdrc_cf_temperatureMaximum: Optional[Quantity] = Field(
        default=None, title="temp range max"
    )
    rdrc_cf_temperatureMinimum: Optional[Quantity] = Field(
        default=None, title="temp range min"
    )
    rdrc_cf_trackedByEhs: Optional[str] = Field(default=None, title="Tracked by EHS")
    rdrc_cf_value_boolean: Optional[bool] = Field(default=None, title="Value")
    rdrc_cf_value_number: Optional[Quantity] = Field(default=None, title="Value")
    rdrc_cf_value_string: Optional[str] = Field(default=None, title="Value")
    rdrc_cf_variablePosition: Optional[bool] = Field(
        default=None, title="Variable Position?"
    )
    rdrc_cf_volume: Optional[Quantity] = Field(default=None, title="Volume")
    rdrc_cf_washTime: Optional[int] = Field(default=None, title="wash time")
    rdrc_cf_washType: Optional[str] = Field(default=None, title="Z Direction")
    rdrc_createdBy: Optional[str] = Field(default=None, title="Created by")
    rdrc_createdOn: Optional[datetime] = Field(default=None, title="Created on")
    rdrc_fk_group: Optional[int] = Field(
        default=None, title="Group", foreign_key="Groups.grps_groupName"
    )
    rdrc_fk_referenceDataType: Optional[int] = Field(
        default=None,
        title="Reference Data Type",
        foreign_key="ReferenceDataType.rdty_name",
    )
    rdrc_fk_user: Optional[int] = Field(
        default=None, title="User", foreign_key="User.user_userName"
    )
    rdrc_modifiedBy: Optional[str] = Field(default=None, title="Modified by")
    rdrc_modifiedOn: Optional[datetime] = Field(default=None, title="Modified on")
    rdrc_name: Optional[str] = Field(default=None, title="Name")
    rdrc_pk: Optional[int] = Field(default=None, title="rdrc_pk", primary_key=True)
    rdrc_uniqueIdentifier: Optional[str] = Field(
        default=None, title="Unique identifier"
    )
