"""
Autogenerated module
"""

from datetime import datetime
from typing import Optional

from sqlmodel import Field, SQLModel


class Unit(SQLModel):
    """
    Autogenerated class for SLIMS table Unit
    """

    __tablename__ = "Unit"

    dmns_name: Optional[str] = Field(default=None, title="Dimension")
    unit_abbreviation: Optional[str] = Field(default=None, title="Abbreviation")
    unit_createdBy: Optional[str] = Field(default=None, title="Created by")
    unit_createdOn: Optional[datetime] = Field(default=None, title="Created on")
    unit_fk_dimension: Optional[int] = Field(
        default=None, title="Dimension", foreign_key="Dimension.dmns_name"
    )
    unit_fk_originalUnit: Optional[int] = Field(
        default=None, title="Original unit", foreign_key="Unit.unit_abbreviation"
    )
    unit_fromOriginalUnitGroovy: Optional[str] = Field(
        default=None, title="Value expression to convert from original unit"
    )
    unit_modifiedBy: Optional[str] = Field(default=None, title="Modified by")
    unit_modifiedOn: Optional[datetime] = Field(default=None, title="Modified on")
    unit_name: Optional[str] = Field(default=None, title="Name")
    unit_pk: int = Field(..., title="unit_pk", primary_key=True)
    unit_prefix: Optional[str] = Field(default=None, title="Prefix")
    unit_seqNo: Optional[str] = Field(default=None, title="Sequence number")
    unit_subDimension: Optional[str] = Field(default=None, title="Sub dimension")
    unit_subdimension: Optional[str] = Field(default=None, title="unit_subdimension")
    unit_suspicious: Optional[bool] = Field(default=None, title="Suspicious")
    unit_toOriginalUnitGroovy: Optional[str] = Field(
        default=None, title="Value expression to convert to original unit"
    )
    unit_type: Optional[str] = Field(default=None, title="Type")
