"""
Autogenerated module
"""

from datetime import datetime
from typing import Optional

from sqlmodel import Field, SQLModel


class Workflow(SQLModel):
    """
    Autogenerated class for SLIMS table Workflow
    """

    __tablename__ = "Workflow"

    wrfl_active: Optional[bool] = Field(default=None, title="Active")
    wrfl_analyticsStrategy: Optional[str] = Field(
        default=None, title="wrfl_analyticsStrategy"
    )
    wrfl_configRenderer: Optional[str] = Field(
        default=None, title="wrfl_configRenderer"
    )
    wrfl_createdBy: Optional[str] = Field(default=None, title="Created by")
    wrfl_createdOn: Optional[datetime] = Field(default=None, title="Created on")
    wrfl_description: Optional[str] = Field(default=None, title="Description")
    wrfl_externalPartyEnricher: Optional[str] = Field(
        default=None, title="wrfl_externalPartyEnricher"
    )
    wrfl_fk_group: Optional[int] = Field(
        default=None, title="Group", foreign_key="Groups.grps_groupName"
    )
    wrfl_fk_queueGridTemplate: Optional[int] = Field(
        default=None,
        title="wrfl_fk_queueGridTemplate",
        foreign_key="GridTemplate.grtm_name",
    )
    wrfl_fk_runGridTemplate: Optional[int] = Field(
        default=None, title="Run grid template", foreign_key="GridTemplate.grtm_name"
    )
    wrfl_fk_user: Optional[int] = Field(
        default=None, title="User", foreign_key="User.user_userName"
    )
    wrfl_isAnalytical: Optional[bool] = Field(default=None, title="Analytical")
    wrfl_modifiedBy: Optional[str] = Field(default=None, title="Modified by")
    wrfl_modifiedOn: Optional[datetime] = Field(default=None, title="Modified on")
    wrfl_name: Optional[str] = Field(default=None, title="Name")
    wrfl_pk: Optional[int] = Field(default=None, title="wrfl_pk", primary_key=True)
    wrfl_presetComments: Optional[str] = Field(default=None, title="Comment")
    wrfl_uniqueIdentifier: Optional[str] = Field(
        default=None, title="Unique identifier"
    )
